# Blog articles. Add a new dict to ARTICLES, then run: python3 build.py
# Body blocks: ("p", text), ("h2", text), ("ul", [items]). HTML is allowed in text.
# Set "partner": True to show the partner-link disclosure under the article.


def A(label, url):
    return f'<a href="{url}" target="_blank" rel="noopener">{label}</a>'


SEFA = A("SEFA", "https://www.sefa.org.za")
NEF = A("NEF", "https://www.nefcorp.co.za")
BP = A("Business Partners", "https://www.businesspartners.co.za")
IDC = A("IDC", "https://www.idc.co.za")
NYDA = A("NYDA", "https://www.nyda.gov.za")
SEDA = A("SEDA", "https://www.seda.org.za")
DSBD = A("Department of Small Business Development", "https://www.dsbd.gov.za")
SARS = A("SARS", "https://www.sars.gov.za")
CIPC = A("CIPC", "https://www.cipc.co.za")
THUNDA = A("Thundafund", "https://www.thundafund.com")
NCR = A("National Credit Regulator", "https://www.ncr.org.za")

ARTICLES = [
    {
        "slug": "where-small-businesses-can-find-funding",
        "date": "2025-10-07",
        "title": "Where South African small businesses can find funding",
        "summary": "A map of the main funding routes, from your own cash flow to development finance and crowdfunding, and how to choose between them.",
        "body": [
            ("p", "Most owners start by asking who will lend to them. A better first question is what the money is for. Funding that suits a delivery van does not suit a slow month, and the wrong match is how businesses end up with debt they cannot service."),
            ("h2", "Match the money to the purpose"),
            ("ul", [
                "<strong>Working capital</strong> (stock, salaries, slow-paying customers): overdraft, supplier terms, invoice finance or a short-term business loan.",
                "<strong>Equipment and vehicles:</strong> asset finance, where the item itself is the security.",
                "<strong>Growth or a new premises:</strong> term loans or development finance, which need a solid plan and track record.",
                "<strong>A first product or launch:</strong> your own savings, family and friends, or crowdfunding.",
            ]),
            ("h2", "Where to look"),
            ("p", f"Start with your own bank, which already sees your account activity. Then look at the development funders: {SEFA} (loans and guarantees for small enterprises), {NEF} (funding for black-owned and empowered businesses), {BP} (finance with mentorship for established businesses) and the {IDC} for larger projects. Young founders can also approach the {NYDA}. For product launches and community-backed ideas, {THUNDA} is a South African crowdfunding platform."),
            ("p", "Each funder has its own criteria, sectors and ticket sizes. Read them before you apply, because a poor-fit application wastes weeks."),
            ("h2", "What every funder wants to see"),
            ("p", "Whatever the source, you will be asked for the same things: bank statements, financial records, proof the business is registered and tax compliant, and a plan for how you will repay. The businesses that get funded fastest are the ones whose records are already in order. That is the subject of next month's article."),
        ],
        "help": ("Funding-ready books", "Lumeo keeps your bookkeeping reconciled every month, so when a funder asks for financials you can send them the same day."),
    },
    {
        "slug": "what-funders-ask-for",
        "date": "2025-11-04",
        "title": "What funders ask for, and how to have it ready",
        "summary": "The documents behind most small business funding applications, and a simple way to keep them ready all year.",
        "body": [
            ("p", "Funding applications stall on paperwork far more often than on the idea. The list below covers what most banks and development funders ask for. Keep it in one folder and update it monthly, and an application becomes an afternoon's work."),
            ("h2", "The standard pack"),
            ("ul", [
                "<strong>Identity and registration:</strong> owner IDs, proof of address and company registration documents. Companies should have annual returns up to date with the " + CIPC + ".",
                "<strong>Tax compliance:</strong> a good-standing tax compliance status from " + SARS + ", plus recent VAT and EMP201 submissions if you are registered.",
                "<strong>Bank statements:</strong> usually six to twelve months for the account your business income goes through.",
                "<strong>Financial records:</strong> annual financial statements, or recent management accounts showing income, expenses and profit.",
                "<strong>Debtors and creditors:</strong> a list of who owes you and who you owe, with ages.",
                "<strong>A plan and forecast:</strong> what you will spend the money on and how cash flow will repay it.",
            ]),
            ("h2", "Why mixing accounts hurts you"),
            ("p", "If personal spending runs through the business account, a funder cannot tell what the business really earns. Separate accounts are the cheapest fix and the one funders notice first."),
            ("h2", "A monthly routine that keeps you ready"),
            ("ul", [
                "Reconcile the bank account after month-end, not at year-end.",
                "Save invoices and receipts the day you get them.",
                "Review debtors and chase anything past its due date.",
                "Save a one-page profit and cash summary each month.",
            ]),
            ("p", f"If you are still choosing a funder, the {SEDA} offers free business support and the {DSBD} lists programmes for small enterprises."),
        ],
        "help": ("We prepare the pack", "Our monthly bookkeeping produces the bank reconciliations, management reports and debtor lists funders ask for."),
    },
    {
        "slug": "surviving-the-january-cash-flow-dip",
        "date": "2025-12-02",
        "title": "Surviving the January cash flow dip",
        "summary": "December brings costs and slow payers, and January brings few sales. Here is how to plan for the gap before it arrives.",
        "body": [
            ("p", "Many small businesses hit their tightest cash position in January. Customers pay late after the holidays, staff bonuses and stock top-ups have gone out, and annual costs such as insurance, licences and school fees land at the same time."),
            ("h2", "Look 13 weeks ahead"),
            ("p", "A simple weekly cash forecast shows the gap while you can still act. List the money you expect in each week, then the money going out: salaries, rent, suppliers, VAT and PAYE. The weeks where the balance turns negative are the ones to solve now."),
            ("h2", "Moves that help before year-end"),
            ("ul", [
                "<strong>Invoice early.</strong> Send December work invoices before you close, not in January.",
                "<strong>Chase what is overdue.</strong> A friendly call or a payment link on the invoice speeds things up.",
                "<strong>Talk to suppliers.</strong> Ask for longer terms on January orders before you need them.",
                "<strong>Set money aside</strong> for VAT, EMP201 and provisional tax so a tax payment does not drain working capital.",
                "<strong>Arrange an overdraft or credit line while cash is healthy.</strong> Lenders say yes more readily when you do not need the money urgently.",
            ]),
            ("h2", "Cut what does not earn"),
            ("p", "Check your bank statement for subscriptions and debit orders you no longer use. Small leaks add up in a tight month."),
        ],
        "help": ("Know your cash position", "Lumeo's Full service plan includes a cash flow forecast and a debtors follow-up list, so you can see the January gap in November."),
    },
    {
        "slug": "set-up-your-business-finances-for-the-new-year",
        "date": "2026-01-06",
        "title": "Set up your business finances for the new year",
        "summary": "A short checklist for starting the year with clean records, a deadline calendar and a simple budget.",
        "body": [
            ("p", "January is a good time to fix the money habits that gave you trouble last year. This checklist takes a few hours and saves many more."),
            ("ul", [
                "<strong>Separate bank account.</strong> One account for the business, and pay yourself a set amount on a set date.",
                "<strong>Accounting records.</strong> We mainly use Xero; keep your records and statements ready to share as Excel or PDF files.",
                "<strong>Simple categories.</strong> Use a short list of income and expense categories that match how you think about the business.",
                "<strong>A document habit.</strong> Photograph or upload every invoice and receipt the day you get it.",
                "<strong>A deadline calendar.</strong> Add the dates below to your phone with a reminder a week before.",
                "<strong>A budget.</strong> Estimate income and costs per month, then compare to actuals at each month-end.",
                "<strong>A price check.</strong> Compare your prices to your costs, which have probably risen.",
            ]),
            ("h2", "Dates to put in the calendar"),
            ("ul", [
                "EMP201 (PAYE, UIF and SDL) submissions: by the 7th of each month.",
                "VAT201 returns: after each VAT period, on the dates SARS publishes for your category.",
                "Provisional tax: the end of August and the end of February for most individuals and sole proprietors.",
                "Annual returns for companies at the " + CIPC + ", based on your registration anniversary.",
            ]),
            ("p", f"Confirm exact dates on {SARS} for your situation."),
        ],
        "help": ("Setup without the headache", "We mainly use Xero, and can work from records shared as Excel or PDF files. You do not need to connect bank feeds or give us access to your apps."),
    },
    {
        "slug": "provisional-tax-without-the-panic",
        "date": "2026-02-03",
        "title": "Provisional tax without the panic",
        "summary": "Who pays provisional tax, when payments fall due, and how monthly books make the estimate far less stressful.",
        "body": [
            ("p", "If you earn income that is not taxed through a salary, such as profit from your own business, you will probably be a provisional taxpayer. Instead of paying one lump sum after year-end, you pay in instalments during the year."),
            ("h2", "How the periods work"),
            ("p", "For individuals and sole proprietors whose tax year ends in February, the first payment is due by the end of August and the second by the end of February. An optional top-up can follow after year-end. Companies pay based on their own financial year-end."),
            ("h2", "Where the stress comes from"),
            ("p", "Each payment is based on an estimate of your taxable income for the whole year. If the estimate is too low, SARS can add penalties. If you have no recent numbers, you are guessing."),
            ("h2", "Make the estimate from your books"),
            ("ul", [
                "Pull the year-to-date profit from your monthly report.",
                "Project the rest of the year using the same months last year as a guide.",
                "Add or remove one-off items such as equipment purchases or a large debtor written off.",
                "Hand the figures to your tax practitioner to complete the return.",
            ]),
            ("h2", "Set money aside as you go"),
            ("p", "Move a fixed percentage of each payment received into a separate savings account. When a provisional payment is due, the cash is already there."),
            ("p", f"Registration and eFiling are done through {SARS}. Your practitioner can tell you which rules apply to you."),
        ],
        "help": ("Numbers ready on time", "Our monthly profit report gives you and your tax practitioner year-to-date figures at any point in the year."),
    },
    {
        "slug": "tax-year-end-gather-your-records",
        "date": "2026-03-03",
        "title": "Tax year-end: gather your records before your practitioner asks",
        "summary": "The tax year for most individuals ended on the last day of February. Here is what to collect for a faster, cheaper return.",
        "body": [
            ("p", "Practitioners charge by time, and much of that time goes on chasing missing documents. Having your records in one place is the simplest way to lower the bill."),
            ("h2", "Collect these first"),
            ("ul", [
                "A year-end income and expense summary from your accounting software.",
                "Bank statements for every business account, plus loan and credit card statements.",
                "Sales invoices and a list of unpaid invoices at year-end.",
                "Purchase invoices and receipts, including asset purchases.",
                "A fixed asset list showing what you bought and when.",
                "Vehicle logbooks if you claim business travel.",
                "Retirement annuity, medical aid and other certificates.",
                "IRP5 or IT3 documents if you also earn a salary.",
            ]),
            ("h2", "Clean up before you send"),
            ("ul", [
                "Make sure every bank transaction is categorised.",
                "Check that personal spending is not mixed into business expenses.",
                "Reconcile the bank account to the last day of the year.",
                "Note anything unusual, such as a large one-off payment.",
            ]),
            ("p", f"Check the filing dates for your return with {SARS} each year, and file on time even if you cannot pay in full."),
        ],
        "help": ("Year-end support", "Our accounting and bookkeeping team prepares organised year-end records and a trial balance to support your filing."),
    },
    {
        "slug": "grants-and-support-programmes",
        "date": "2026-04-07",
        "title": "Grants, support programmes and what they really cost",
        "summary": "Free money is rare. Support programmes are not, and they come with their own work. How to find genuine ones and avoid scams.",
        "body": [
            ("p", "Search for small business grants and you will find a lot of promises. Real grants exist, but they are competitive, tied to specific sectors or groups, and usually come with reporting duties."),
            ("h2", "Genuine places to start"),
            ("ul", [
                SEDA + ": free business support, training and referrals.",
                DSBD + ": information on government programmes for small enterprises.",
                NYDA + ": support and grants for young entrepreneurs.",
                SEFA + " and " + NEF + ": finance rather than grants, but with support attached.",
            ]),
            ("h2", "Warning signs of a scam"),
            ("ul", [
                "You are asked to pay a fee, a deposit or a processing charge to receive a grant.",
                "The offer arrives by WhatsApp or a social media message you did not ask for.",
                "The website is not a recognised government or funder domain.",
                "You are pressured to act quickly or keep the offer secret.",
            ]),
            ("p", "If in doubt, go to the organisation's official site directly and call the number listed there."),
            ("h2", "Count the real cost"),
            ("p", "Programmes often ask for financial statements, proof of tax compliance, progress reports and sometimes proof of how funds were spent. If you are not already keeping records, the application will take weeks. If you are, it takes days."),
        ],
        "help": ("Records that satisfy reporting", "We keep a clear paper trail for every rand spent, which makes programme reports and audits much easier."),
    },
    {
        "slug": "do-you-need-to-register-for-vat",
        "date": "2026-05-05",
        "title": "Do you need to register for VAT?",
        "summary": "The thresholds, the trade-offs of registering early, and when turnover tax might suit you better.",
        "body": [
            ("p", "VAT registration is compulsory once your taxable turnover exceeds R1 million in any consecutive 12-month period. You may register voluntarily once it passes R50 000. Thresholds can change, so check " + SARS + " for the current figures."),
            ("h2", "Reasons to register"),
            ("ul", [
                "You can claim back VAT charged on business purchases (input VAT).",
                "Larger customers and tenders often expect a VAT number.",
                "Registering signals that the business is established.",
            ]),
            ("h2", "Reasons to wait"),
            ("ul", [
                "You must charge VAT, which makes you 15% more expensive to customers who cannot claim it.",
                "You must keep proper tax invoices and submit returns on time.",
                "VAT collected is not your money. It has to be set aside until it is paid over.",
            ]),
            ("h2", "A different option for very small businesses"),
            ("p", "Micro businesses with turnover under R1 million can choose turnover tax, a simplified regime that replaces income tax, VAT and some other taxes. It reduces admin but has its own limits, so ask your practitioner before switching."),
            ("h2", "Whichever you choose"),
            ("p", "Keep sales invoices in sequence, record every payment against the invoice, and track the date your rolling 12-month turnover crosses R1 million. Missing the point you became liable is expensive."),
        ],
        "help": ("VAT, handled", "Our Standard plan includes VAT201 and EMP201 preparation, with working papers filed so you can see how every figure was reached."),
    },
    {
        "slug": "taking-card-payments-what-to-look-for",
        "date": "2026-06-02",
        "title": "Taking card payments: what to look for",
        "summary": "How to compare card payment providers, with iKhokha as one example, and how card settlements show up in your books.",
        "partner": True,
        "body": [
            ("p", "Customers increasingly expect to pay by card or phone. Offering it can lift sales, reduce cash handling and give you cleaner records. The challenge is choosing a provider that fits how you work."),
            ("h2", "What to compare"),
            ("ul", [
                "<strong>Upfront and monthly cost:</strong> some providers rent machines monthly, others sell them once-off.",
                "<strong>Transaction fees:</strong> check the percentage for card-present and online payments, and whether it drops as volumes grow.",
                "<strong>Settlement speed:</strong> how many days before the money reaches your bank.",
                "<strong>Hardware:</strong> a dedicated machine, or tap-to-pay on a phone you already own.",
                "<strong>Online options:</strong> payment links and checkout tools if you sell remotely.",
                "<strong>Reporting:</strong> whether you can export sales and settlements as Excel or PDF files for your accounting and bookkeeping records.",
                "<strong>Support and lock-in:</strong> contract terms and what happens if you stop.",
            ]),
            ("h2", "One option: iKhokha"),
            ("p", "iKhokha is a South African provider offering portable card machines, Tap on Phone, payment links and invoices, and a free app that tracks sales. Devices are sold once-off rather than rented, and rates depend on your volumes. We explain it further on our " + '<a href="../recommended.html#ikhokha">recommended tools page</a>' + ". Compare it with at least one other provider before you decide."),
            ("h2", "How card sales appear in your books"),
            ("p", "Your bank will show a settlement, not individual sales, and the provider's fee will already be deducted. To keep income accurate, record the gross sale, record the fee as an expense, and reconcile the settlement to both. If you skip that step, your income looks lower than it really is and your fees disappear."),
        ],
        "help": ("Card sales, reconciled", "We reconcile card settlements to your sales every month and record fees correctly, so your profit figure can be trusted."),
    },
    {
        "slug": "know-your-margins-before-you-change-prices",
        "date": "2026-07-07",
        "title": "Know your margins before you change your prices",
        "summary": "The difference between margin and markup, why overheads matter, and how to test a price change before you make it.",
        "body": [
            ("p", "Many owners set prices by looking at competitors, then hope the numbers work. A few minutes with your own costs shows whether they do."),
            ("h2", "Margin and markup are not the same"),
            ("p", "If an item costs R60 and you sell it for R100, your gross profit is R40. That is a 40% margin (profit as a share of the selling price) but a 67% markup (profit as a share of cost). Mixing them up is the most common pricing mistake, and it leads to prices that are too low."),
            ("h2", "Work out your real cost"),
            ("ul", [
                "Direct costs: materials, stock, subcontractors and the time it takes to deliver.",
                "Overheads: rent, software, insurance, transport, bank fees and card fees.",
                "Your own pay. If you do not pay yourself, the business is subsidised by you.",
            ]),
            ("h2", "Test before you change"),
            ("ul", [
                "Calculate the gross margin for each product or service, not just the business overall.",
                "Find your break-even sales level: overheads divided by gross margin percentage.",
                "Model a price rise. A small increase can offset losing a few customers.",
                "Test on new customers first and watch the monthly numbers.",
            ]),
            ("p", "A business that grows sales but sells most of them at a poor margin is working harder to earn less."),
        ],
        "help": ("Margins by product", "Our monthly report shows income, direct costs and gross profit so you can price from facts instead of instinct."),
    },
    {
        "slug": "protect-yourself-not-only-the-business",
        "date": "2026-08-04",
        "title": "Protect yourself, not only the business",
        "summary": "For many owners the business is the main source of income. What personal insurance covers, what it does not, and where to start.",
        "partner": True,
        "body": [
            ("p", "When you run the business, your car, laptop, phone and home are working assets. A theft or accident can interrupt income straight away. Business insurance gets most of the attention, but the personal side deserves a look too."),
            ("h2", "What personal insurance can cover"),
            ("ul", [
                "<strong>Your car:</strong> comprehensive cover for the vehicle you drive to clients.",
                "<strong>Specific items:</strong> a laptop, phone or camera you cannot work without. Check how business use and travel are treated.",
                "<strong>Home contents and buildings:</strong> especially if you work from home.",
            ]),
            ("p", 'Naked is one South African digital insurer offering these. We describe it on our <a href="../recommended.html#naked">recommended tools page</a>. Get quotes from more than one insurer and read the policy wording.'),
            ("h2", "What it does not replace"),
            ("ul", [
                "<strong>Business insurance</strong> for stock, equipment, business interruption and liability.",
                "<strong>Income protection, disability and life cover</strong> through a licensed financial adviser.",
                "<strong>An emergency fund.</strong> Insurance pays after a loss, and an excess still has to come from somewhere.",
            ]),
            ("h2", "Keep the money side tidy"),
            ("p", "Insurance premiums, excesses and replacements are easier to manage when personal and business money are separate. Pay yourself a regular amount, and pay personal premiums from your own account."),
        ],
        "help": ("Separate the money", "We help you set up a clean split between business and personal finances and show you what the business can safely pay you."),
    },
    {
        "slug": "funding-without-a-bank-loan",
        "date": "2026-09-01",
        "title": "Funding without a bank loan: crowdfunding, invoice finance and supplier terms",
        "summary": "Alternatives to a traditional loan, what they cost, and how to check a lender before you sign.",
        "body": [
            ("p", "A bank loan is not the only route, and for many small businesses it is not the available one. These alternatives suit different situations."),
            ("h2", "Options to consider"),
            ("ul", [
                "<strong>Crowdfunding.</strong> Platforms such as " + THUNDA + " let supporters back a product or project. It works best when you have an audience and a clear reward to offer.",
                "<strong>Invoice finance.</strong> A funder advances part of what a customer owes you and collects when they pay. It frees cash but costs more than a loan.",
                "<strong>Supplier terms.</strong> Negotiate 30 or 60 days instead of cash on delivery. It is free, if you pay on time.",
                "<strong>Customer deposits.</strong> Ask for a deposit on larger orders so you can buy materials.",
                "<strong>Equipment finance.</strong> Spread the cost of vehicles or machinery over time.",
                "<strong>Development finance</strong> from " + SEFA + ", " + NEF + " or " + BP + ", which can be cheaper than commercial credit.",
            ]),
            ("h2", "Check the real cost"),
            ("p", "Compare offers by the total you will pay back, not the headline fee. A short-term advance with a small fee can work out expensive when you annualise it. Ask for the repayment schedule in writing."),
            ("h2", "Check the lender"),
            ("p", f"Credit providers must be registered. Look up any lender on the {NCR} site before you share bank details or sign. Be wary of anyone who asks for a payment before a loan is approved."),
            ("h2", "Plan the repayment first"),
            ("p", "Before you borrow, show on paper how repayments fit into cash flow in your slowest month. If they do not, adjust the amount or choose a different route."),
        ],
        "help": ("Compare the true cost", "We help you work out what each option really costs and whether your cash flow can carry the repayments."),
    },
    {
        "slug": "five-things-to-do-before-december",
        "date": "2026-10-01",
        "title": "Five things to do before December",
        "summary": "The last quarter is the cheapest time to fix problems. Five jobs that make year-end and January easier.",
        "body": [
            ("p", "By October, the year's habits are set. The next three months are your chance to tidy up before holidays, bonuses and slow January trading."),
            ("h2", "1. Clear the bookkeeping backlog"),
            ("p", "If transactions are months behind, catch up now. It is far harder to reconstruct a year in February than in October."),
            ("h2", "2. Review who owes you"),
            ("p", "Run a debtors list and follow up everything past its due date. Cash collected before the festive shutdown carries you into January."),
            ("h2", "3. Forecast the next quarter"),
            ("p", "Map expected income and costs week by week through January. If a gap appears, line up an overdraft, supplier terms or a customer deposit now."),
            ("h2", "4. Check your tax position"),
            ("p", "Compare year-to-date profit with what you estimated for provisional tax. Set money aside for the February payment and any VAT or PAYE falling due."),
            ("h2", "5. Review your tools and cover"),
            ("p", 'Check that your payment tools, software subscriptions and insurance still fit. Our <a href="../recommended.html">recommended tools page</a> lists options, and our <a href="surviving-the-january-cash-flow-dip.html">January cash flow article</a> goes deeper on the forecast.'),
            ("h2", "Book year-end help early"),
            ("p", "Accountants and bookkeepers get busy in January and February. If you want support at year-end, ask now."),
        ],
        "help": ("Close the year well", "Book a call and we will tell you where your books stand and what to fix before year-end."),
    },
]
